from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from pydantic import BaseModel, ConfigDict
from typing import Any

from app.core.database import get_db
from app.core.deps import get_current_user
from app.models.user import User
from app.models.recommendation import Recommendation
from app.ml.inference import generate_recommendation, generate_multi_horizon_recommendation

router = APIRouter()


class RecommendationOut(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    id: str
    generated_at: str
    confidence: float
    model_version: str
    is_cold_start: bool
    next_workout: Any
    weekly_plan: list[Any]
    insights: list[Any]
    forecast: Any
    risks: list[Any]


@router.get("/recommendation", response_model=RecommendationOut)
async def get_recommendation(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    # Return latest cached recommendation if fresh (< 6 hours)
    result = await db.execute(
        select(Recommendation)
        .where(Recommendation.user_id == current_user.id)
        .order_by(desc(Recommendation.generated_at))
        .limit(1)
    )
    rec = result.scalar_one_or_none()

    from datetime import datetime, timedelta, timezone
    from sqlalchemy import select as _sel
    from app.models.user import AthleteProfile
    if rec:
        age = datetime.now(timezone.utc) - rec.generated_at.replace(tzinfo=timezone.utc)
        if age < timedelta(hours=6):
            # Invalidate cache if profile has a strength approach but cached payload
            # has no strength sessions (generated before strength feature was added).
            prof_res = await db.execute(
                _sel(AthleteProfile).where(AthleteProfile.user_id == current_user.id)
            )
            prof = prof_res.scalar_one_or_none()
            approach = (prof.strength_approach or "friel") if prof else "friel"
            if approach != "none":
                plan = rec.payload.get("weekly_plan", [])
                has_strength = any(
                    w.get("is_strength") or w.get("strength_addon") or w.get("gtg_practice")
                    for w in plan
                )
                if not has_strength:
                    rec = None  # force regeneration

            # Bust cache if payload carries risk warnings — they may have been
            # generated by old logic (ramp_rate formula) and are now stale/wrong.
            # Fresh generation uses the fixed ATL/CTL ratio + TSB gate guards.
            if rec and rec.payload.get("risks"):
                rec = None  # force regeneration

            # Bust cache if payload lacks multi-horizon structure — generated
            # before the horizons feature was added or after a schema change.
            if rec and "horizons" not in rec.payload:
                rec = None

            if rec:
                return _rec_out(rec)

    # Generate fresh recommendation
    rec = await generate_recommendation(current_user, db)
    db.add(rec)
    await db.flush()
    return _rec_out(rec)


@router.post("/recommendation/refresh", response_model=RecommendationOut)
async def refresh_recommendation(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    rec = await generate_recommendation(current_user, db)
    db.add(rec)
    await db.flush()
    return _rec_out(rec)


# ── Multi-horizon: 3 alternative recommendations side-by-side ────────────────
class MultiHorizonOut(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    """
    Three alternative "next workout" suggestions, one per planning horizon:
      • short  — best for 7-day FTP gain
      • medium — best for 28-day build
      • event  — best path to peak on the user's goal-event date
    Each horizon's payload mirrors the standard RecommendationOut shape.
    Also includes a rule-based supplement stack derived from training load
    and (if available) the user's latest blood test.
    """
    is_cold_start:  bool
    model_version:  str
    active_horizon: str
    horizons:       dict[str, Any]
    supplements:    dict[str, Any] | None = None


@router.get("/recommendation/multi-horizon", response_model=MultiHorizonOut)
async def get_multi_horizon_recommendation(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns 3 alternative recommendations side-by-side so the user can pick
    based on their current priority (immediate gain vs long-term peak).
    Always fresh — does not use the 6h cache.
    """
    return await generate_multi_horizon_recommendation(current_user, db)


# ── Macrocycle: reverse-periodization plan from event date back to today ─────
@router.get("/macrocycle")
async def get_macrocycle(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    days: int | None = None,  # horizon override in days (7/28/90); None = use event date
):
    """
    Returns a week-by-week plan from today through the user's goal_event_date,
    reverse-engineered to peak ON event day. Combines the event_type bias with
    a CTL ramp model (Banister/Coggan).

    When `days` is provided a virtual event date (today + days) is used instead
    of goal_event_date so each horizon tab shows a genuinely different ramp.

    Returns 404 if the user has no goal_event_date set AND no days override.
    """
    from app.models.user import AthleteProfile
    from app.models.recommendation import FitnessMetric
    from app.ml.macrocycle import build_macrocycle
    from datetime import datetime, timezone, timedelta

    profile_result = await db.execute(
        select(AthleteProfile).where(AthleteProfile.user_id == current_user.id)
    )
    profile = profile_result.scalar_one_or_none()

    today = datetime.now(timezone.utc)

    if days is not None:
        # Horizon-scoped view: virtual event at today + days.
        # For short/medium tabs there may be no real event, so we use a
        # generic goal type. The ramp will reflect the shorter window.
        virtual_event_date = today + timedelta(days=days)
        event_type  = profile.event_type  if profile else None
        event_name  = f"{days}-day horizon"
        training_days = (profile.training_days_per_week or 5) if profile else 5
        ftp         = (profile.ftp or 250.0) if profile else 250.0
    else:
        if not profile or not profile.goal_event_date:
            from fastapi import HTTPException
            raise HTTPException(
                404, "No goal event set. Set goal_event_date in profile to use macrocycle planning."
            )
        virtual_event_date = profile.goal_event_date
        event_type  = profile.event_type
        event_name  = profile.goal_event_name
        training_days = profile.training_days_per_week or 5
        ftp         = profile.ftp or 250.0

    metric_result = await db.execute(
        select(FitnessMetric)
        .where(FitnessMetric.user_id == current_user.id)
        .order_by(desc(FitnessMetric.date))
        .limit(1)
    )
    latest = metric_result.scalar_one_or_none()
    ctl = latest.ctl if latest else 0.0
    atl = latest.atl if latest else 0.0

    return build_macrocycle(
        current_ctl=ctl,
        current_atl=atl,
        event_date=virtual_event_date,
        event_type=event_type,
        event_name=event_name,
        training_days_per_week=training_days,
        ftp=ftp,
    )


@router.get("/analyze/{activity_id}")
async def analyze_activity(
    activity_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    from app.models.activity import Activity
    result = await db.execute(
        select(Activity).where(
            Activity.id == activity_id,
            Activity.user_id == current_user.id,
        )
    )
    activity = result.scalar_one_or_none()
    if not activity:
        from fastapi import HTTPException
        raise HTTPException(404, "Activity not found")

    from app.ml.inference import analyze_single_activity
    analysis = await analyze_single_activity(activity, current_user, db)
    return analysis


def _rec_out(rec: Recommendation) -> RecommendationOut:
    p = rec.payload
    return RecommendationOut(
        id=rec.id,
        generated_at=rec.generated_at.isoformat(),
        confidence=rec.confidence,
        model_version=rec.model_version,
        is_cold_start=rec.is_cold_start,
        next_workout=p.get("next_workout"),
        weekly_plan=p.get("weekly_plan", []),
        insights=p.get("insights", []),
        forecast=p.get("forecast"),
        risks=p.get("risks", []),
    )


# ── Feedback: did the user accept / modify / reject the suggestion? ──────────
class FeedbackIn(BaseModel):
    """Payload for POST /coach/recommendation/{id}/feedback."""
    action: str                                  # accepted | modified | rejected | skipped
    post_ride_rpe: int | None = None             # 1–10
    modified_workout_type: str | None = None     # e.g. "endurance"
    modified_duration_min: int | None = None
    comment: str | None = None


_VALID_ACTIONS = {"accepted", "modified", "rejected", "skipped"}


@router.post("/recommendation/{rec_id}/feedback")
async def post_recommendation_feedback(
    rec_id: str,
    payload: FeedbackIn,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Capture what the user did with a suggestion.

    Append-only: every call inserts a new feedback row (no deduplication —
    the user can also send a follow-up row later with their post-ride RPE).
    Used for personalization (Phase 3 LoRA fine-tuning) and monitoring.
    """
    from fastapi import HTTPException
    from app.models.outcome import RecommendationFeedback

    if payload.action not in _VALID_ACTIONS:
        raise HTTPException(400, f"action must be one of {sorted(_VALID_ACTIONS)}")
    if payload.post_ride_rpe is not None and not (1 <= payload.post_ride_rpe <= 10):
        raise HTTPException(400, "post_ride_rpe must be between 1 and 10")

    # Verify the recommendation belongs to this user (prevent IDOR).
    result = await db.execute(
        select(Recommendation).where(
            Recommendation.id == rec_id,
            Recommendation.user_id == current_user.id,
        )
    )
    rec = result.scalar_one_or_none()
    if not rec:
        raise HTTPException(404, "Recommendation not found")

    fb = RecommendationFeedback(
        recommendation_id=rec_id,
        user_id=current_user.id,
        action=payload.action,
        post_ride_rpe=payload.post_ride_rpe,
        modified_workout_type=payload.modified_workout_type,
        modified_duration_min=payload.modified_duration_min,
        comment=payload.comment,
    )
    db.add(fb)
    await db.flush()
    return {"id": fb.id, "ok": True}


@router.post("/outcomes/backfill")
async def backfill_outcomes(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Manually trigger the prediction-vs-actual backfill for the current user.

    Normally this is run by a scheduled worker, but exposing it lets the user
    refresh their personal accuracy dashboard on demand and lets us verify
    the job in dev without Celery.
    """
    from app.ml.outcomes import backfill_user_outcomes
    n = await backfill_user_outcomes(current_user.id, db)
    return {"ok": True, "outcomes_written": n}

